Debug = true
LogFileName = 'run.log'
LogOutputs = ['file', 'console']
Version = '1'
[APIGateway]
AddressField = 'IP'
BreakerDashboard = true
BreakerErrorPercentThreshold = 10
BreakerLimitAPI = true
BreakerLimitIP = true
BreakerLimitUser = true
BreakerMaxConcurrentRequest = 10
BreakerRequestTimeout = 10
BreakerRequestVolumeThreshold = 10
BreakerSleepWindow = 10
Disabled = false
EID = '42b72128a473438e881e5b4e53c8ab2a'
UseBreaker = false
UserField = 'User'

[ApAuthService]
DatabaseKey = ''
DefaultPwd = 'Qaz@2020'
Disabled = false
EID = 'c21f4f863a974fb182c9ae4cf05dc142'
LimitedSlots = ''
LockAfterFails = 5
Name = 'ap'
OutAddressField = 'ip'
OutAgentField = 'agent'
PwdEncoding = 'base64'
PwdMaxLen = 8
PwdMinLen = 6
PwdNumberAndLetter = false
PwdSecret = ''
PwdSymbol = false
PwdSymbols = '{{base64:JF4mKigpPXx7fSc6IVtdXy0rfi48Pg==}}'
PwdUpperAndLowerLetter = false
SessionCreateSlot = 'CreateToken'
SessionRevokeSlot = 'RevokeToken'
SessionService = 'session'
SessionVerifySlot = 'VerifyToken'
SuperFailed = 0
SuperFails = 3
SuperName = 'root'
SuperPwd = 'dd6e5e5918e94d997c686fcebc56922f'

[DataService]
Disabled = false
EID = 'e946fb6305874b44a375a030e0f75a68'
LimitedSlots = ''
Name = 'data'

[DatabasePlugin]
Disabled = false
EID = '2b1c22654bb141b8ae247ae7246a8f54'
[[DatabasePlugin.Connections]]
InitData = false
InitDataAfterSecond = 30
InitDataDir = '.'
Key = 'mysql'
MaxIdleConns = 0
MaxOpenConns = 0
Name = 'demo'
Port = 33060
Pwd = 'www@admin@2020'
ReadTimeout = 10
Reset = false
Server = '172.16.10.214'
SingularTable = false
Type = 'mysql'
User = 'root'
WriteTimeout = 10


[FileService]
CleanFs = false
DatabaseKey = ''
Disabled = false
EID = '9e200ad9094c40de9bed3caa09cf992d'
Hash = 'sha256'
LimitedSlots = ''
MinioBucket = 'default'
Name = 'file'
Storage = 'fs'

[HASDemoPlugin]
Disabled = false
EID = 'a1aba05d8dc844ab98785505e54aea9a'
Name = 'HAS'

[HelloService]
Disabled = false
EID = '12e7f0321f414843847f0dbd7bc13244'
LimitedSlots = ''
Name = 'hello'

[JsonPacker]
Disabled = false
EID = '7ea759ade4034d1189bca34b8d7357d9'

[LocalRouter]
Disabled = false
EID = '8d7cf47c77d845bbaea22849a2f84777'

[LockerMiddleware]
APIList = ['v1:login,addUser']
AddressField = ''
Disabled = false
EID = '03d8a5e4eb1a4f2c93ca0c32182eae01'
LockDuration = 0
MaxFails = 10
Model = 'whitelist'
UserField = 'User'

[MemCachePlugin]
CleanupDuration = 10
Disabled = false
EID = '1f81aca2f78d4d0cb8265ffcbf73c48d'
ExpireDuration = 10

[PermMiddleware]
Disabled = false
EID = '3daa1c3f297f4e17a7614392c332da20'

[Server]
Disabled = false
EID = 'e12e44e473834be08cdee8cda258724f'
MaxProcs = 0
PprofPort = 6060

[SessionMiddleware]
APIWhiteList = ['v1:login,addUser']
Disabled = false
EID = '8b074664f8c642e18ef4366e0e8134b8'
InAddressField = 'IP'
InAgentField = 'Agent'
InTokenField = 'Token'
InUserField = 'User'
OutAddressField = 'ip'
OutAgentField = 'agent'
OutTokenField = 'token'
OutUserField = 'user'
SessionService = 'session'
VerifySlot = 'VerifyToken'

[SessionService]
CheckAgent = false
CheckIP = false
CheckUser = false
DatabaseKey = ''
Disabled = false
EID = '8a99579371c842d2ab342c7ae0c6477d'
LimitedSlots = ''
MagicToken = 'a1b2@c3d4'
Name = 'session'
SessionsPerUser = 1
TokenExpire = 10080

[TestMiddleware]
Disabled = false
EID = '3e1315d22300460483da277221373582'

[TestService]
Disabled = false
EID = '57884b2103834956ac6e523ae7a5cdc0'
LimitedSlots = ''
Name = 'test'
TestBool = true
TestName = 'HAS'

[WebConnector]
AddressField = 'IP'
AppKey = ''
AppSecret = ''
BodyLimit = 999999
Disabled = false
EID = '38f832644e834eb8ad8c46a1c9a0d0c9'
Lang = ''
Packer = 'JsonPacker'
Port = 8989
SignMethod = ''
Timeout = 0
Tls = false
TlsCertPath = ''
TlsKeyPath = ''
WebSocketEnabled = false
WebSocketUrl = ''

